### ISSUE TITLE
some merge conflicts issues

### ISSUE THREAD

**Issue by denismartens** [GreenMonkeys/GreenMonkeyChess#26] opened 2015-03-14 04:00 UTC
@kenmazaika 

Hey Ken,

As you can tell our current build is not passing. There is pull request #11 that hasn't been merged in but it contains a migration (adding name field to game) that is needed for a test in the current master too pass. I've been trying to pull that request #11 and get it merged in to current master or my piece_move branch but get this error when running rake (for every test where Game.create... is called ):

NoMethodError: undefined method `email' for #Game:0xbb1a82e8

I also cannot successfully run all the migrations. 

Can you suggest what I should do here? Is this a case where I should delete all old migrations and create a new one based on the schema?

**Comment by Neilda** [comment] 2015-03-14 05:57
Hey Denis,

I'm working on #11 merge conflicts right now.

Neilda

On Fri, Mar 13, 2015 at 9:00 PM, Denis Martens notifications@github.com
wrote:

> @kenmazaika https://github.com/kenmazaika
> 
> Hey Ken,
> 
> As you can tell our current build is not passing. There is pull request
> #11 https://github.com/GreenMonkeys/GreenMonkeyChess/pull/11 that
> hasn't been merged in but it contains a migration (adding name field to
> game) that is needed for a test in the current master too pass. I've been
> trying to pull that request #11
> https://github.com/GreenMonkeys/GreenMonkeyChess/pull/11 and get it
> merged in to current master or my piece_move branch but get this error when
> running rake (for every test where Game.create... is called ):
> 
> NoMethodError: undefined method `email' for #Game:0xbb1a82e8
> 
> I also cannot successfully run all the migrations.
> 
> Can you suggest what I should do here? Is this a case where I should
> delete all old migrations and create a new one based on the schema?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GreenMonkeys/GreenMonkeyChess/issues/26.

## 

_Neilda Pacquing_
UX Designer

_Email:_ neilda@neildapacquing.com
_Skype:_ neilda.pacquing
*Portfolio: *www.neildapacquing.com
*Github: *https://github.com/Neilda  https://github.com/Neilda
*LinkedIn: *https://www.linkedin.com/in/neildapacquing

**Comment by Neilda** [comment] 2015-03-14 06:46
Check it out now. I believe it should work.

On Fri, Mar 13, 2015 at 10:56 PM, Neilda Pacquing <neilda@neildapacquing.com

> wrote:
> 
> Hey Denis,
> 
> I'm working on #11 merge conflicts right now.
> 
> Neilda
> 
> On Fri, Mar 13, 2015 at 9:00 PM, Denis Martens notifications@github.com
> wrote:
> 
> > @kenmazaika https://github.com/kenmazaika
> > 
> > Hey Ken,
> > 
> > As you can tell our current build is not passing. There is pull request
> > #11 https://github.com/GreenMonkeys/GreenMonkeyChess/pull/11 that
> > hasn't been merged in but it contains a migration (adding name field to
> > game) that is needed for a test in the current master too pass. I've been
> > trying to pull that request #11
> > https://github.com/GreenMonkeys/GreenMonkeyChess/pull/11 and get it
> > merged in to current master or my piece_move branch but get this error when
> > running rake (for every test where Game.create... is called ):
> > 
> > NoMethodError: undefined method `email' for #Game:0xbb1a82e8
> > 
> > I also cannot successfully run all the migrations.
> > 
> > Can you suggest what I should do here? Is this a case where I should
> > delete all old migrations and create a new one based on the schema?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GreenMonkeys/GreenMonkeyChess/issues/26.
> 
> ## 
> 
> _Neilda Pacquing_
> UX Designer
> 
> _Email:_ neilda@neildapacquing.com
> _Skype:_ neilda.pacquing
> *Portfolio: *www.neildapacquing.com
> *Github: *https://github.com/Neilda  https://github.com/Neilda
> *LinkedIn: *https://www.linkedin.com/in/neildapacquing

## 

_Neilda Pacquing_
UX Designer

_Email:_ neilda@neildapacquing.com
_Skype:_ neilda.pacquing
*Portfolio: *www.neildapacquing.com
*Github: *https://github.com/Neilda  https://github.com/Neilda
*LinkedIn: *https://www.linkedin.com/in/neildapacquing

**Comment by kenmazaika** [comment] 2015-03-14 13:54
Cool, cool.  I think the reason Travis might have a failure is a legacy thing because the pull request has been around awhile, the last time the test suite ran for the code things were different. 

Hopefully Neilda's change fixes it.  If it doesn't, can you include the full stack trace of the error?

**Comment by denismartens** [comment] 2015-03-14 17:24
Thanks Neilda and Ken! It is better now, but our current build still isn't passing because not all migrations have been run? https://travis-ci.org/GreenMonkeys/GreenMonkeyChess.

**Comment by kenmazaika** [comment] 2015-03-14 19:27
It looks like the problem is we have an invalid database migration that got merged in.  When I start with a fresh database and run the migrations I see this:

```
== 20150225141255 AddOpponentId: migrating ====================================
-- add_column(:games, :opponent_id, :integer)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "opponent_id" of relation "games" already exists
: ALTER TABLE "games" ADD COLUMN "opponent_id" integer/vagrant/src/GreenMonkeyChess/db/migrate/20150225141255_add_opponent_id.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
```

When I comment out this line the migrations run properly.  

https://github.com/GreenMonkeys/GreenMonkeyChess/blob/master/db/migrate/20150225141255_add_opponent_id.rb#L3

Then I get this error when I run the tests:

```
.......................E

Finished in 17.597799s, 1.3638 runs/s, 16.7066 assertions/s.

  1) Error:
GamesControllerTest#test_someone_is_logged_in-_new:
NoMethodError: undefined method `generate=' for #<User:0xbb792dd4>
    test/controllers/games_controller_test.rb:14:in `block in <class:GamesControllerTest>'

```

Line 14 is a line that's calling factory girl on the users.  When I jump into the `test/factories.rb` file and adjust the user factory to be valid it works like a charm:

```
FactoryGirl.define do
  factory :user do
    sequence :email do |n|
      "person#{n}@example.com"
    end

    password "passpassword1"
    password_confirmation "passpassword1"
  end

  factory :game do
        name "tough game"
  end
end
```

I believe if you make a pull request with those changes, should work like a charm.

**Comment by denismartens** [comment] 2015-03-15 03:48
Awesome! That did it.

**Closed as completed** 2015-03-15 03:48 UTC
